version: '3.4'

services:
  ptm-server:
    image: iemam/platformtm-server:unicorn1.5
    build:
      context: PlatformTM-server
      dockerfile: PlatformTM.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    volumes:
      - "ptmappdata:/app_data"
  ptm-web:
    image: iemam/platformtm-web:unicorn1.5
    build:
      context: PlatformTM-web
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - ptm-server
    volumes:
      - "./nginx-server.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"

volumes:
  ptmappdata:
