version: '2'

services:
  mongo:
    image: mongo:3.4
    restart: unless-stopped
    volumes:
      - "mongodata:/data/db"
  mariadb:
    image:  mariadb:10.1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=imperial
      - MYSQL_DATABASE=ptmdb
    volumes:
      - "mariadata:/var/lib/mysql"
  ptm-server:
    image: platformtm-server
    build:
      context: PlatformTM-server
      dockerfile: PlatformTM.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: unless-stopped
    depends_on:
      - mongo
      - mariadb
    volumes:
      - "ptmappdata:/app_data"
  ptm-web:
    image: platformtm-web
    build:
      context: PlatformTM-web
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - ptm-server
    volumes:
      - "./nginx-server.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8889:80"
#  db-init:
#    image: ptmdb-init
#    build:
#      context: PlatformTM-server
#      dockerfile: Dockerfile.db-init
#    volumes:
#      - "./PlatformTM-initdb/:/docker-entrypoint-initdb.d/"
#    depends_on:
#      - mariadb

volumes:
  mongodata:
  mariadata:
  ptmappdata:
