version: '2'

services:
  mongo:
    image: mongo:3.4
    restart: unless-stopped
    volumes:
      - "mongodata:/data/db"
  mariadb:
    image:  mariadb:10.1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=imperial
      - MYSQL_DATABASE=ptmdb
    volumes:
      - "mariadata:/var/lib/mysql"
  ptm-server:
    image: platform-tm/platform-tm-server
    restart: unless-stopped
    depends_on:
      - mongo
      - mariadb
    volumes:
      - "ptmappdata:/app_data"
  ptm-web:
    image: platform-tm/platform-tm-web
    restart: unless-stopped
    depends_on:
      - ptm-server
    volumes:
      - "./nginx-server.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8889:80"
  db-init:
    image: platform-tm/db-init
    volumes:
      - "./db-init/:/docker-entrypoint-initdb.d/"
    depends_on:
      - mariadb
      
volumes:
  mongodata:
  mariadata:
  ptmappdata:
